version: '3'
services:
    nginx:
        image: nginx:1.10
        working_dir: /var/www
        volumes:
            - ./docker/nginx/conf:/etc/nginx/conf.d/
            - ./:/var/www
        networks:
            default:
            test:
                aliases:
                    - website
    php:
        image: php:7-fpm
        working_dir: /var/www
        volumes:
            - ./:/var/www
        networks:
            default:
                aliases:
                    - phpfpm
            test:
networks:
    test:
        external:
            name: test