version: '3'
services:
    mariadb:
        image: mariadb:10
        environment:
            - MYSQL_ROOT_PASSWORD=root
        ports:
          - 3306:3306
        networks:
            default:
                aliases:
                    - mysql
networks:
    default:
        external:
            name: test